export const Config = {
  CUSTOMER_SERVICE_API: process.env.REACT_APP_CUSTOMER_SERVICE_API,
  CUSTOMER_MASTER_API: process.env.REACT_APP_MASTER_SERVICE_API,
  CUSTOMER_BOOKING_SERVICE_API: process.env.REACT_APP_BOOKING_SERVICE_API,
  NOTIFICATION_SERVICE_API: process.env.REACT_APP_NOTIFICATION_SERVICE_API,
  IMAGE_URL: "",
  CAPTCHA_KEY: "6LcI_ksmAAAAADaoxE88Rb3T8IOdYoncBMbCmwMg",
};
